
version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-grocysync}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-grocysync_password}
      POSTGRES_DB: ${POSTGRES_DB:-grocysync}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-grocysync}:${POSTGRES_PASSWORD:-grocysync_password}@postgres:5432/${POSTGRES_DB:-grocysync}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
      PORT: ${API_PORT:-3001}
      NODE_ENV: ${NODE_ENV:-development}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5173}
    ports:
      - "${API_PORT:-3001}:3001"
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3001}
    env_file:
      - .env

volumes:
  postgres_data:
